/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AguardandoRouteImport } from './routes/aguardando'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AppHistoricoRouteImport } from './routes/_app.historico'
import { Route as AppPainelRouteImport } from './routes/_app.painel'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppTarefasRouteImport } from './routes/_app.tarefas'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminAtividadesRouteImport } from './routes/_app.admin.atividades'
import { Route as AppAdminRelatoriosRouteImport } from './routes/_app.admin.relatorios'
import { Route as AppAdminUsuariosRouteImport } from './routes/_app.admin.usuarios'
import { Route as AppAdminSupervisorProfileIdRouteImport } from './routes/_app.admin.supervisor.$profileId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoRoute = AguardandoRouteImport.update({
  id: '/aguardando',
  path: '/aguardando',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppPainelRoute = AppPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasRoute = AppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAtividadesRoute = AppAdminAtividadesRouteImport.update({
  id: '/admin/atividades',
  path: '/admin/atividades',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRelatoriosRoute = AppAdminRelatoriosRouteImport.update({
  id: '/admin/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsuariosRoute = AppAdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSupervisorProfileIdRoute =
  AppAdminSupervisorProfileIdRouteImport.update({
    id: '/admin/supervisor/$profileId',
    path: '/admin/supervisor/$profileId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aguardando': typeof AguardandoRoute
  '/cadastro': typeof CadastroRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/historico': typeof AppHistoricoRoute
  '/painel': typeof AppPainelRoute
  '/perfil': typeof AppPerfilRoute
  '/tarefas': typeof AppTarefasRoute
  '/admin/atividades': typeof AppAdminAtividadesRoute
  '/admin/relatorios': typeof AppAdminRelatoriosRoute
  '/admin/usuarios': typeof AppAdminUsuariosRoute
  '/admin/': typeof AppAdminIndexRoute
  '/admin/supervisor/$profileId': typeof AppAdminSupervisorProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando': typeof AguardandoRoute
  '/cadastro': typeof CadastroRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/historico': typeof AppHistoricoRoute
  '/painel': typeof AppPainelRoute
  '/perfil': typeof AppPerfilRoute
  '/tarefas': typeof AppTarefasRoute
  '/admin/atividades': typeof AppAdminAtividadesRoute
  '/admin/relatorios': typeof AppAdminRelatoriosRoute
  '/admin/usuarios': typeof AppAdminUsuariosRoute
  '/admin': typeof AppAdminIndexRoute
  '/admin/supervisor/$profileId': typeof AppAdminSupervisorProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/aguardando': typeof AguardandoRoute
  '/cadastro': typeof CadastroRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/painel': typeof AppPainelRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/tarefas': typeof AppTarefasRoute
  '/_app/admin/atividades': typeof AppAdminAtividadesRoute
  '/_app/admin/relatorios': typeof AppAdminRelatoriosRoute
  '/_app/admin/usuarios': typeof AppAdminUsuariosRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/admin/supervisor/$profileId': typeof AppAdminSupervisorProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aguardando'
    | '/cadastro'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/historico'
    | '/painel'
    | '/perfil'
    | '/tarefas'
    | '/admin/atividades'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/admin/'
    | '/admin/supervisor/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando'
    | '/cadastro'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/historico'
    | '/painel'
    | '/perfil'
    | '/tarefas'
    | '/admin/atividades'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/admin'
    | '/admin/supervisor/$profileId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/aguardando'
    | '/cadastro'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/_app/historico'
    | '/_app/painel'
    | '/_app/perfil'
    | '/_app/tarefas'
    | '/_app/admin/atividades'
    | '/_app/admin/relatorios'
    | '/_app/admin/usuarios'
    | '/_app/admin/'
    | '/_app/admin/supervisor/$profileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AguardandoRoute: typeof AguardandoRoute
  CadastroRoute: typeof CadastroRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando': {
      id: '/aguardando'
      path: '/aguardando'
      fullPath: '/aguardando'
      preLoaderRoute: typeof AguardandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/painel': {
      id: '/_app/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AppPainelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tarefas': {
      id: '/_app/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AppTarefasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/atividades': {
      id: '/_app/admin/atividades'
      path: '/admin/atividades'
      fullPath: '/admin/atividades'
      preLoaderRoute: typeof AppAdminAtividadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/relatorios': {
      id: '/_app/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AppAdminRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/usuarios': {
      id: '/_app/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AppAdminUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/supervisor/$profileId': {
      id: '/_app/admin/supervisor/$profileId'
      path: '/admin/supervisor/$profileId'
      fullPath: '/admin/supervisor/$profileId'
      preLoaderRoute: typeof AppAdminSupervisorProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppPainelRoute: typeof AppPainelRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppTarefasRoute: typeof AppTarefasRoute
  AppAdminAtividadesRoute: typeof AppAdminAtividadesRoute
  AppAdminRelatoriosRoute: typeof AppAdminRelatoriosRoute
  AppAdminUsuariosRoute: typeof AppAdminUsuariosRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppAdminSupervisorProfileIdRoute: typeof AppAdminSupervisorProfileIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoricoRoute: AppHistoricoRoute,
  AppPainelRoute: AppPainelRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppTarefasRoute: AppTarefasRoute,
  AppAdminAtividadesRoute: AppAdminAtividadesRoute,
  AppAdminRelatoriosRoute: AppAdminRelatoriosRoute,
  AppAdminUsuariosRoute: AppAdminUsuariosRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppAdminSupervisorProfileIdRoute: AppAdminSupervisorProfileIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AguardandoRoute: AguardandoRoute,
  CadastroRoute: CadastroRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
